CREATE TABLE ESTADO (
    SGESTADO char(2) NOT NULL,

    Primary Key (SGESTADO)
);

CREATE TABLE CIDADE (
    CDCIDADE int NOT NULL AUTO_INCREMENT,
    SGESTADO char(2) NOT NULL,
    NMCIDADE varchar(20) NOT NULL,

    Primary Key (CDCIDADE, SGESTADO),
    Foreign Key (SGESTADO) REFERENCES ESTADO (SGESTADO)
);

CREATE TABLE BAIRRO (
    CDBAIRRO int NOT NULL AUTO_INCREMENT,
    CDCIDADE int NOT NULL,
    SGESTADO char(2) NOT NULL,
    NMBAIRRO varchar(20) NOT NULL,

    Primary Key (CDBAIRRO, CDCIDADE, SGESTADO),
    Foreign Key (CDCIDADE) REFERENCES CIDADE (CDCIDADE),
    Foreign Key (SGESTADO) REFERENCES ESTADO (SGESTADO)
);

CREATE TABLE VENDEDOR (
    CDVENDEDOR int NOT NULL AUTO_INCREMENT,
    NMVENDEDOR varchar(40) NOT NULL,
    NMENDERECO varchar(40) NOT NULL,
    NRCPF decimal(11) NOT NULL,
    NMCIDADE varchar(20) NOT NULL,
    NMBAIRRO varchar(20) NOT NULL,
    SGESTADO char(2) NOT NULL,
    TELEFONE varchar(20) NOT NULL,
    EMAIL varchar(80) NOT NULL,

    Primary Key (CDVENDEDOR)
);

CREATE TABLE IMOVEL (
    CDIMOVEL int NOT NULL AUTO_INCREMENT,
    CDVENDEDOR int NOT NULL,
    CDBAIRRO int NOT NULL,
    CDCIDADE int NOT NULL,
    SGESTADO char(2) NOT NULL,
    NMENDERECO varchar(40) NOT NULL,
    NRAREAUTIL decimal(10,2),
    NRAREATOTAL decimal(10,2),
    DSIMOVEL varchar(300),
    VLPRECO decimal(16,2) NOT NULL,
    NROFERTAS int NOT NULL,
    STVENDIDO char(1) NOT NULL,
    DTLANCTO date,
    IMOVEL_INDICADO int,

    Primary Key (CDIMOVEL),
    Foreign Key (CDVENDEDOR) REFERENCES VENDEDOR (CDVENDEDOR),
    Foreign Key (CDBAIRRO) REFERENCES BAIRRO (CDBAIRRO)
);

CREATE TABLE OFERTA (
    CDIMOVEL int NOT NULL,
    CDCOMPRADOR int NOT NULL,
    VLOFERTA decimal(16,2) NOT NULL,
    DTOFERTA date NOT NULL,

    Primary Key (CDIMOVEL, CDCOMPRADOR),
    Foreign Key (CDIMOVEL) REFERENCES IMOVEL (CDIMOVEL),
    Foreign Key (CDCOMPRADOR) REFERENCES COMPRADOR (CDCOMPRADOR)
);

CREATE TABLE FAIXA_IMOVEL (
    CDFAIXA int NOT NULL AUTO_INCREMENT,
    NMFAIXA varchar(30),
    VLMINIMO decimal(14,2),
    VLMAXIMO decimal(14,2),

    Primary Key (CDFAIXA)
);