SELECT c.CDCOMPRADOR, c.NMCOMPRADOR, v.CDVENDEDOR, v.NMVENDEDOR 
FROM COMPRADOR c, VENDEDOR v
ORDER BY CDCOMPRADOR;

SELECT v.NMVENDEDOR, i.NMENDERECO 
FROM VENDEDOR v, IMOVEL i
WHERE v.CDVENDEDOR = i.CDVENDEDOR AND i.CDIMOVEL 
IN (SELECT o.CDIMOVEL FROM OFERTA o WHERE o.CDCOMPRADOR = 2) OR i.CDBAIRRO = 1;

SELECT c.NMCOMPRADOR FROM COMPRADOR c 
WHERE c.CDCOMPRADOR NOT IN (SELECT o.CDCOMPRADOR FROM OFERTA o);

SELECT NMENDERECO, CDVENDEDOR, STVENDIDO,
CASE
	When STVENDIDO = "N" Then "Disponivel" 
	When STVENDIDO = "S" Then "Vendido"
END
FROM IMOVEL;
