CREATE VIEW vImovel_Bairro1 AS
SELECT CDIMOVEL, NMENDERECO, VLPRECO FROM IMOVEL
WHERE CDBAIRRO = 1;

CREATE VIEW vImovel_Cidade AS
SELECT AVG(VLPRECO), CDCIDADE, SGESTADO FROM IMOVEL
group by CDCIDADE;
