CREATE VIEW vlmovel_Bairro1 AS
SELECT CDIMOVEL, NMENDERECO, VLPRECO FROM IMOVEL
WHERE CDBAIRRO = 1;

CREATE VIEW vlmovel_Cidade AS
SELECT AVG(VLPRECO), CDCIDADE, SGESTADO FROM IMOVEL
group by CDCIDADE;
